// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static void aCT_ShowUploadPage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_ShowUploadPage").withParams(params).execute(context);
	}
	public static void aCT_SubmitUpload(IContext context, excelimporter.proxies.TemplateDocument _templateDocument)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TemplateDocument", _templateDocument == null ? null : _templateDocument.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SubmitUpload").withParams(params).execute(context);
	}
	/**
	 * Example how you can implement your own excel import file
	 * 
	 * Retrieve a template, this can be  from an association or by the use of a constant or some application settings. How exactly the template is retrieved does not really matter. 
	 * 
	 * Next, if the template is found the import java action should be executed. This java action has three parameters. The first parameter is the retrieved template, the second parameter is the excel file. The third parameter is an optional parameter this parameter can contain an object in case you want to set the reference from all imported objects to the object from the parameter.
	 * 
	 */
	public static myfirstmodule.proxies.ExcelHeader_Data iVK_ImportTemplateDocument_DataExcel(IContext context, excelimporter.proxies.TemplateDocument _templateDocument)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TemplateDocument", _templateDocument == null ? null : _templateDocument.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.IVK_ImportTemplateDocument_DataExcel").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.ExcelHeader_Data.initialize(context, result);
	}
}
