// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Data_NP
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject data_NPMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Data_NP";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TanggalLahir("TanggalLahir"),
		Data_NP_ExcelHeader_Data("MyFirstModule.Data_NP_ExcelHeader_Data");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Data_NP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Data_NP(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject data_NPMendixObject)
	{
		if (data_NPMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, data_NPMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.data_NPMendixObject = data_NPMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Data_NP.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Data_NP initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Data_NP.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Data_NP initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Data_NP(context, mendixObject);
	}

	public static myfirstmodule.proxies.Data_NP load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Data_NP.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TanggalLahir
	 */
	public final java.lang.String getTanggalLahir()
	{
		return getTanggalLahir(getContext());
	}

	/**
	 * @param context
	 * @return value of TanggalLahir
	 */
	public final java.lang.String getTanggalLahir(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TanggalLahir.toString());
	}

	/**
	 * Set value of TanggalLahir
	 * @param tanggallahir
	 */
	public final void setTanggalLahir(java.lang.String tanggallahir)
	{
		setTanggalLahir(getContext(), tanggallahir);
	}

	/**
	 * Set value of TanggalLahir
	 * @param context
	 * @param tanggallahir
	 */
	public final void setTanggalLahir(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tanggallahir)
	{
		getMendixObject().setValue(context, MemberNames.TanggalLahir.toString(), tanggallahir);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Data_NP_ExcelHeader_Data
	 */
	public final myfirstmodule.proxies.ExcelHeader_Data getData_NP_ExcelHeader_Data() throws com.mendix.core.CoreException
	{
		return getData_NP_ExcelHeader_Data(getContext());
	}

	/**
	 * @param context
	 * @return value of Data_NP_ExcelHeader_Data
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.ExcelHeader_Data getData_NP_ExcelHeader_Data(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.ExcelHeader_Data result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Data_NP_ExcelHeader_Data.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.ExcelHeader_Data.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Data_NP_ExcelHeader_Data
	 * @param data_np_excelheader_data
	 */
	public final void setData_NP_ExcelHeader_Data(myfirstmodule.proxies.ExcelHeader_Data data_np_excelheader_data)
	{
		setData_NP_ExcelHeader_Data(getContext(), data_np_excelheader_data);
	}

	/**
	 * Set value of Data_NP_ExcelHeader_Data
	 * @param context
	 * @param data_np_excelheader_data
	 */
	public final void setData_NP_ExcelHeader_Data(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ExcelHeader_Data data_np_excelheader_data)
	{
		if (data_np_excelheader_data == null) {
			getMendixObject().setValue(context, MemberNames.Data_NP_ExcelHeader_Data.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Data_NP_ExcelHeader_Data.toString(), data_np_excelheader_data.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return data_NPMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Data_NP that = (myfirstmodule.proxies.Data_NP) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
